services:
  service-name:
    build:
      context: ./${PROJECT_NAME}/.build
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}_image
    volumes:
      - ./${PROJECT_NAME}:${CONTAINER_VOLUME:-/app}
    working_dir: ${CONTAINER_VOLUME:-/app}
    environment:
      - PYTHONPATH=${PYTHONPATH:-/app:/app/stock_price}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-my_gemini_api_key}
      - GH_TOKEN=${GH_TOKEN:-my_github_token}
    # command: ["bash", "run.sh"]
    stdin_open: true
    tty: true